version: "3"
services:
  previewer:
    image: demacr/image_previewer:latest
    container_name: previewer
    ports:
      - "8080:8080"
    environment:
      HOST: "0.0.0.0"
      PORT: 8080
      CACHE_CAPACITY: 100
    restart: always
