kind: pipeline
type: docker
name: image_previewer

steps:
- name: lint
  image: golangci/golangci-lint:v1.32.2-alpine
  commands:
    - golangci-lint run ./...
- name: "unit tests"
  image: golang
  commands:
    - make test-unit
- name: "integration tests"
  image: demacr/docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
    - make test-integration
- name: build
  image: demacr/docker:dind
  environment:
    DOCKERHUB_TOKEN:
      from_secret: DOCKERHUB_TOKEN
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start
  - docker login -u demacr -p $DOCKERHUB_TOKEN
  - make build-push

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}

trigger:
  branch:
  - master
